### ISSUE TITLE
fail to add package from SPM

### ISSUE THREAD

**Issue by LonYui** [MarcoDotIO/OpenAIKit#31]
### Describe the bug

i am try to install it . but fail
with err msg
```

Showing Recent Messages
package at 'https://github.com/MarcoDotIO/OpenAIKit' @ 2e6ad42b94ac283697a0affe41f9e9cd235a7777 is using Swift tools version 5.7.0 but the installed version is 5.5.0 in https://github.com/MarcoDotIO/OpenAIKit


```

### To Reproduce

1. open xcode any project
2. File -> add package
3. search for "https://github.com/MarcoDotIO/OpenAIKit"
4. click add package

### Code snippets

```Swift
no code just xcode UI interact
```

### OS

11.6.5

### Swift Version

Swift 5.5

### Xcode Version

Xcode 13.2.1

### Library version

OpenAikit 1.1.1

**Comment by MarcoDotIO** [comment]
Hello,

What iOS / macOS / watchOS / tvOS target version is your project?

**Comment by MarcoDotIO** [comment]
Actually hold that thought, looked it up and 5.5 is backwards compatible with iOS 13 and similar Apple hardware versions. I will be making a version later today that incorporates multiple Swift versions down to 5.5. Thank you for bringing this up!

**Comment by MarcoDotIO** [comment]
Alright @LonYui please let me know if 1.1.2 reports the same errors for your project. I'd be happy to help further, as I have now added the different package variations for Swift 5.5 and 5.6.

**Comment by MarcoDotIO** [comment]
Closing the issue, assuming the issue has been resolved. Please reopen if any further problems arise.

**Comment by LonYui** [comment]
i just test. it's pass ✅. thx!!


MarcoDotIO ***@***.***> 於 2022年12月18日 週日 上午2:03寫道：
