### ISSUE TITLE
Add GPT-4 Support

### ISSUE THREAD

**Issue by stormychel** [MarcoDotIO/OpenAIKit#40]
### Describe the feature or improvement you're requesting

Please add support for https://openai.com/research/gpt-4

If you are not yet working on this and want me to look into it please let me know.

Thanks!

**Comment by MarcoDotIO** [comment]
This will be implemented in the next revision update for OpenAIKit as an Enum object. Refer to #41.

**Comment by stormychel** [comment]
Awesome, let me know if I can help!

**Comment by jtnessler** [comment]
GPT-4 uses the same endpoint as GPT-3.5.  Just use the model modifier.
