### ISSUE TITLE
OpenAI has no member 'decondeBase64Image'

### ISSUE THREAD

**Issue by nievesatla** [MarcoDotIO/OpenAIKit#46]
### Describe the bug

Currently I am writing an image generation call for a new vision OS app. when I try and decode base 64 image, there is an error that comes up. Maybe this is due to the OS I am using? Unsure what the fix would be, I am attaching my code below. 

### To Reproduce

1. Download the latest beta version of xcode (I am on xcode 15 beta 8)
2. create a new app repo with the vision OS version 1.0
3. Enter the below code.

### Code snippets

```Swift
import OpenAIKit
final class imageGenerator: ObservableObject {
    private var openai: OpenAI?
    
    func setup() {
        let openai = OpenAI(Configuration(
            organizationId: "Personal",
            apiKey: "[API Key Here]"
        ))
    }
    
    func generateImage(prompt: String) async -> UIImage? {
        guard let openai = openai else {
            return nil
        }
        
        do{
            let params = ImageParameters(
                prompt: prompt,
                resolution: .medium,
                responseFormat: .base64Json
            )
            let result = try await openai.createImage(parameters: params)
            let data = result.data[0].image
            let image = try openai.decodeBase64Image(data)
            return image
            
        }
        catch {
            print(String(describing: error))
        }
    }
}
```

### OS

visionOS 1.0 beta 3

### Swift Version

Unspecified

### Xcode Version

Xcode 15 Beta 8

### Library version

OpenAIKit version 1.2.0

**Comment by MarcoDotIO** [comment]
Hello,

I'm currently reinstalling the visionOS SDK at the moment, but for the time being, I'd recommend downloading the package from the `main` branch; as I've implemented several new features. I'll have a 2.0 update released officially around the time of OpenAI's Dev Day (Nov 4th), as I am currently working on finalizing some aspects of the update. Below is how the selection should look before redownloading the package for your project.

![Screenshot 2023-10-27 at 12 03 50 PM](https://github.com/MarcoDotIO/OpenAIKit/assets/20867620/184d9c7d-26f9-401d-a793-44ad18904ec7)

**Comment by MarcoDotIO** [comment]
Alright, the hot fix has been pushed out. Let me know if you're having any other issues building for visionOS.

**Comment by MarcoDotIO** [comment]
@nievesatla

**Comment by nievesatla** [comment]
Hi Marco, thank you so much for the speedy response! I just texted and the error went away, you are the best! I'm going to close with this comment.
